function [ output_args ] = fkl_second( w,g,eps,V )
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
output_args = 2/(sqrt(w'*g*g'*w) - sqrt(eps*w'*w))^4 *...
    (3*(1/sqrt(w'*g*g'*w)*g*g'*w - sqrt(eps)/sqrt(w'*w)*w)...
      *(1/sqrt(w'*g*g'*w)*g*g'*w - sqrt(eps)/sqrt(w'*w)*w)'...
    - sqrt(eps)*sqrt(w'*g*g'*w)*(w'*w)^(-3/2)*w*w' + sqrt(eps)/sqrt(w'*w)...
    *sqrt(w'*g*g'*w)*eye(V)+eps/(w'*w)*w*w'-eps*eye(V));


%*(1/sqrt(w'*g*g'*w)*g*g'*w - sqrt(eps)...
  %  /sqrt(w'*w)w)/(sqrt(w'*g*g'*w) - sqrt(eps*w'*w))^4;

end

